export const TOP_SPANISH_CITIES = [
  'Madrid',
  'Barcelona',
  'Valencia',
  'Sevilla',
  'Zaragoza',
  'Málaga',
  'Murcia',
  'Palma de Mallorca',
  'Las Palmas de Gran Canaria',
  'Bilbao',
  'Alicante',
  'Córdoba',
  'Valladolid',
  'Vigo',
  'Gijón',
  'Granada',
  'A Coruña',
  'Vitoria-Gasteiz',
  'Elche',
  'Oviedo',
  'Badalona',
  'Cartagena',
  'Terrassa',
  'Jerez de la Frontera',
  'Sabadell',
  'Santa Cruz de Tenerife',
  'Pamplona',
  'Almería',
  'Fuenlabrada',
  'Leganés',
  'San Sebastián',
  'Burgos',
  'Santander',
  'Castellón de la Plana',
  'Getafe',
  'Alcorcón',
  'Salamanca',
  'Tarragona',
  'Huelva',
  'Lleida',
  'Marbella',
  'León',
  'Cádiz',
  'Jaén',
  'Ourense',
  'Lugo',
  'Girona',
  'Toledo',
  'Guadalajara',
  'Pontevedra',
  'Torrejón de Ardoz',
  'Parla',
  'Alcobendas',
  'Ibiza',
  'Benidorm',
  'Torrevieja',
  'Estepona',
  'Fuengirola',
  'Torremolinos',
  'Móstoles',
];
